### PR TITLE
HW2

### PR DESCRIPTION
**Pull request by Nicgscode**

### CODE REVIEW

**Comment by stevertaylor** [comment]
@Nicgscode, where are the lecture notebooks from last week?

**Comment by stevertaylor** [comment]
@Nicgscode, the PR still needs the completed Lectures 4 and 5 from last week.

**Comment by Nicgscode** [comment]
Hey sorry,

 I will be able to get them in by Saturday I had a rough week

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Nicgscode** [comment]
Okay I can push them and update them later

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Nicgscode** [comment]
> @Nicgscode, where are the lecture notebooks from last week?

Everything is pushed!

**Comment by stevertaylor** [comment]
Thank you!

**Pull request merged**
